source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!


target 'BXProgressHUD_Example' do
  pod "BXProgressHUD", :path => "../"
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'BXProgressHUD_Tests' do
  pod "BXProgressHUD", :path => "../"

  
end
