source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXProgressHUD_Example', :exclusive => true do
  pod "BXProgressHUD", :path => "../"
end

target 'BXProgressHUD_Tests', :exclusive => true do
  pod "BXProgressHUD", :path => "../"

  
end
